### PR TITLE
some improvement suggestions for Readme.md file

### PR DESCRIPTION
**Pull request by TheBigBear**
And another rewording I would suggest. In the web interface you have a section on top right labelled. "Runned jobs", that is not good english, I think. Not quite sure what to suggest instead. Maybe "Past jobs" or "Job History" or "previously run jobs" , but 'runned' jsut doesn't look right.

### CODE REVIEW

**Comment by Lothiraldan** [comment]
Awesome thx!

**Comment by Lothiraldan** [comment]
About the interface itself, I could tell you where you can modify it yourself it you want.

**Comment by TheBigBear** [comment]
@Lothiraldan hi, the interface is not a big bother, just thought you might want to change that phrase of 'runned' jobs, as it is grammatically wrong, and it will stick out to native english speakers, especially since it is so prominent. "run" is an irregular english verb. run goes from  run running runs ran, never runned.
I run the job
I am running the job
He runs the job
I ran the job
He ran the job
We have run the job
We ran the job

So the straight translation would be 'Ran jobs' or 'Run jobs' , but either of those "hurt" and would not generally be used in thia short and ambiguous form as a button or action label by native english speakers.

**Comment by TheBigBear** [comment]
@Lothiraldan we have ourselves a catch 22 situation now, now that you have merged my changes in that remove the '#' comments from settings.json.sample, the text in the README asking users twice to change settings.json and remove all comments starting with '#' is no longer relevant or making sense either. Sorry about that.

**Comment by TheBigBear** [comment]
@Lothiraldan sorry my bad. 

Just seen that you correclty held back merging that chnage to the sample file. Which I think is right not to merge it, especially now that the README does mention the need to remove the commnets in both applicable sections. 

I had missed the comment because I had been looking ta the 'deploy' section and not at the 'vagrant' testing section at first.

**Comment by Lothiraldan** [comment]
I have not merged https://github.com/tinyclues/saltpad/pull/109 yet, maybe we can close #109 and see if others users have problems for writing the configuration file, what do you think?

**Comment by TheBigBear** [comment]
Yes, I agree. I think it should be closed.

**Pull request merged**
