### PR TITLE
Merge pull request #10 from TheBigBear/TheBigBear-fix-mixed-content-blockage

### PR DESCRIPTION
**Pull request by TheBigBear**
This fixes issue #115

### CODE REVIEW

**Comment by Lothiraldan** [comment]
Thank you for the contribution, could you try to make a PR which consists of only one commit?

**Comment by TheBigBear** [comment]
@Lothiraldan I tried, tried very hard, but whatever trick I think off, in the end a new PR always pulls in all the local commits. 
I guess two options. 

Option 1
Close this PR and do the edit yourself, removing those five characters ```http:``` from the 'app/assets/css/style.css' file

Option 2 
Merge this PR 'as-is' as it will only make one single change in one single file. the rest is just merges and commits that don't change anything in the repo as far as files go

Very sorry, but I can't recover from this any other way.

**Comment by Lothiraldan** [comment]
If you don't have any other modification on your repository, I recommend you to get your master branch at the same status as upstream with this command: `git reset --hard https://github.com/tinyclues/saltpad.git master`. Then `git push -f` to your repository. At this state your master will be the same as the upstream master (on this repository).

Then you can create a new branch and make the modification, create a new PR from this new branch and I will merge it. Then later you will be able to update your master branch with this command: `git pull https://github.com/tinyclues/saltpad.git`.

I understand that I can do the change myself, I've the diff but I'm would take time to clarify the contribution process if you're willing to do more contributions in the future. If you don't have time right now, I will do the commit myself so it can be included in a v0.2 release.

**Comment by TheBigBear** [comment]
Thanks for this. but when trying to run the cmds you gave I get:
```fatal: Invalid object name 'https'.```

Will keep looking ...

**Comment by Lothiraldan** [comment]
My bad, always always test command before. Here is the validated instructions:

First add a new remote for upstream:
`git remote add upstream https://github.com/tinyclues/saltpad.git/`

Update upstream repository:
`git fetch upstream`

Then reset to match upstream master branch:
`git reset --hard upstream/master`

And push to origin master:
`git push -f`

At this state, you can now create a branch, do the commit and create a PR. Hope it helps this time.

**Comment by TheBigBear** [comment]
OK, thanks. The new one is at: https://github.com/tinyclues/saltpad/pull/129

**Pull request closed without merging**
