### PR TITLE
import used modules

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**

### CODE REVIEW

**Comment by Lothiraldan** [comment]
Thank you very much, the code in core.py is used by saltpad CLI and need a good big refactoring, are you interested in saltpad CLI?

**Comment by h4ck3rm1k3** [comment]
I am working https://github.com/h4ck3rm1k3/salt-formulas on a collection of salt and checking all the code for bugs. Sure I am interested in learning more about the saltpad but first i need to learn more salt.

**Comment by Lothiraldan** [comment]
Very cool, about the two novapost repositories, I don't think they will be update any more. I've started them a long time ago when I was working over there, but now we store saltpad under this repository.

**Comment by h4ck3rm1k3** [comment]
thanks, I will work on sorting by active date. If the repos are stale will delete them. but for now I want a body of salt code for testing.

**Pull request merged**
