### PR TITLE
Create a docker container for dev/test; Add venv/ to .gitignore.

### PR DESCRIPTION
**Pull request by alex-leonhardt**
I thought it'd be nice to have a quick n easy docker container image for quick testing / deving.
Alex

### CODE REVIEW

**Comment by Lothiraldan** [comment]
Hi, thank you very much for the Pull-Request, I'm not very comfortable with docker but I cannot see where you install the salt-api, is it in another container?

**Comment by alex-leonhardt** [comment]
Salt api needs to run on the master no? This container will literally just
run saltpad, nothing more. One will need to mod the local_settings.docker
file and update the api URL/IP then build the container and voilà working
saltpad.

Alex

**Comment by Lothiraldan** [comment]
Oh okay, it's a testing container for saltpad only. So people will need to run salt-api somewhere for testing saltpad. Could you please make this more explicit in the readme?

If we had a salt-api container, it would be doable to have a full-testing stack powered by docker, right?

**Comment by alex-leonhardt** [comment]
Correct, I'll do that later this / next week - already have a docker salt
master, just need to install the api and I'm done ;).

Ok I'll update the readme tomorrow.

Alex

**Comment by Lothiraldan** [comment]
Great I will merge it and give it a try after I figure out how to use docker on Mac OS

**Pull request merged**
